// Complements (does not replace) browser-download QA. Only the isolated QA server.
import {build} from 'esbuild';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {read,utils} from 'xlsx';
import {monthlyMatrixRows} from '../../lib/hr/monthly-position.mjs';
const origin='http://127.0.0.1:4179';
const position=await (await fetch(origin+'/api/data?kind=attendance.monthly_position&month=2026-09')).json();
assert.equal(position.batch.source_name,'release19-synthetic-monthly.xlsx');
assert.equal(position.rows.length,1);assert.equal(position.rows[0].name,'موظف اختبار وردية مسائية');
assert.equal(position.metrics.complete,2);assert.equal(position.metrics.worked_minutes,1135);
const out=new URL('../../outputs/release19/',import.meta.url);await mkdir(out,{recursive:true});
const compiled=new URL('./engine.mjs',out);
await build({entryPoints:['lib/hr/exports.ts'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:fileURLToPath(compiled)});
const {tableExcelBytes,tablePdfBytes}=await import(compiled.href);
const request=globalThis.fetch;globalThis.fetch=(input,init)=>request(typeof input==='string'&&input.startsWith('/')?origin+input:input,init);
const headers=(from,to)=>['الكود الوظيفي','الموظف','القسم','الحركة',...Array.from({length:to-from+1},(_,i)=>String(from+i)),'مكتمل','ناقص','بلا بصمات','مراجعة','دقائق موثقة'];
const date=value=>new Intl.DateTimeFormat('ar-IQ',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Baghdad'}).format(new Date(value+'T12:00:00Z'));
const legend='+1 خروج اليوم التالي؛ ناقص خروج غير مسجل؛ — لا قيمة موثقة. الملخص الشهري مكرر للرجوع ولا يُجمع عبر أجزاء الأيام.';
const report={title:'الموقف الشهري بالبصمة',period:`${date('2026-09-01')} · ${date('2026-09-10')} — ${date('2026-09-12')} · حضور معتمد · كل الأقسام · كل المسؤولين · كل الحالات · ${legend}`,headers:headers(1,30),rows:monthlyMatrixRows(position)};
const xlsx=tableExcelBytes(report);const sheet=read(xlsx,{type:'array'});const cells=utils.sheet_to_json(sheet.Sheets[sheet.SheetNames[0]],{header:1,defval:''});
assert.ok(cells.flat().includes('01:30 (+1)'));assert.ok(cells.flat().includes(1135));assert.ok(cells.flat().includes('FANU-000207'));
const segments=Array.from({length:3},(_,i)=>({headers:headers(i*10+1,i*10+10),rows:monthlyMatrixRows(position,i*10+1,i*10+10),columnWeights:[10,18,13,5,...Array(10).fill(6),5,5,5,5,7]}));
const pdf=await tablePdfBytes({...report,segments,fontBase64:(await readFile('public/fonts/DejaVuSans.ttf')).toString('base64')});
assert.equal((Buffer.from(pdf).toString('latin1').match(/\/Type \/Page\b/g)||[]).length,3);
await writeFile(new URL('monthly.xlsx',out),xlsx);await writeFile(new URL('monthly.pdf',out),pdf);
const result={source:'isolated browser QA database + actual application export engine; browser file receipt is a separate gate',rows:2,day_cells:60,complete:2,incomplete:1,worked_minutes:1135,xlsx_bytes:xlsx.length,pdf_bytes:pdf.length,pdf_pages:3,xlsx_sha256:createHash('sha256').update(xlsx).digest('hex')};
await writeFile(new URL('export-verification.json',out),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
